CREATE TABLE dbo.Item (
    [id] UNIQUEIDENTIFIER PRIMARY KEY,
    [title] NVARCHAR(200) NOT NULL,
    [summary] NVARCHAR(200) NOT NULL
);


ALTER DATABASE [ItemDB]
SET CHANGE_TRACKING = ON
(CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON);

ALTER TABLE [dbo].[Item]
ENABLE CHANGE_TRACKING;